
#
#   make - synchronize
#

    all:directories
	cp src/camera-download-manager bin/camera-download-manager

#
#   make - directories
#

    directories:
	mkdir -p bin

#
#   make - clean
#

    clean:
	rm bin/* -f
