
#
#   make - synchronize
#

    all:directories
	cp src/camera-ssh-disks-umount bin/camera-ssh-disks-umount

#
#   make - directories
#

    directories:
	mkdir -p bin

#
#   make - clean
#

    clean:
	rm bin/* -f
