
#
#   make - synchronize
#

    all:directories
	cp src/camera-fastcal-generator-flips bin/camera-fastcal-generator-flips

#
#   make - directories
#

    directories:
	mkdir -p bin

#
#   make - clean
#

    clean:
	rm bin/* -f
