
#
#   make - synchronize
#

    all:directories
	# cp src/camera-fastcal-generator bin/camera-fastcal-generator

#
#   make - directories
#

    directories:
	mkdir -p bin

#
#   make - clean
#

    clean:
	rm bin/* -f
