
#
#   make - synchronize
#

    all:directories
	cp src/camera-downloader-build-modules bin/camera-downloader-build-modules

#
#   make - directories
#

    directories:
	mkdir -p bin

#
#   make - clean
#

    clean:
	rm bin/* -f
